# Dependencies
markdown:         kramdown
highlighter:      rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed

# Permalinks
# permalink:        pretty
# relative_permalinks: true

# Setup
title:            z430
description:      'A Blog'
baseurl:          '/'

author:
  name:           'z430'
  url:            https://twitter.com/mays

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/z430

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive

excerpt_separator: "<!--excerpt-->"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]