title: ByTensor
email: maystya@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Sticky notes
baseurl: "" # the subpath of your site, e.g. /blog
domain: z430.github.io
url: "https://z430.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: maystya
github_username:  z430

permalink: /:slug.html

favicon: "logo.png" # name+extension of favicon (which must be put on the root folder)

theme: no-style-please

theme_config:
  appearance: "dark" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: false # show blog description in home page

plugins:
  - jekyll-feed
  - jekyll-seo-tag


