# Site
name: "z430 Blog"
baseurl: ''
google_analytics: 'UA-161588273-1'
disqus: 'z430-github-io'

# Setup
title:            z430 Blog
baseurl:          ''

# Authors
authors:
  mays:
    name: Mays
    display_name: Mays
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: maystya@gmail.com
    web: https://www.z430.github.io
    twitter: https://twitter.com/maystya
    description: "Share Unimportant Notes"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    

# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

paginate:         5


github:
  repo:           https://github.com/z430
